# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "inclusivedesign/windows10-eval-x64"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.hostname = "win10"
  config.vm.network "public_network"
  config.vm.network :forwarded_port, host: 33389, guest: 3389
  config.vm.provider :virtualbox do |v|
    v.gui = false
    v.memory = 4096
    v.cpus = 2
  end
  config.vm.provider "hyperv" do |h|
    h.cpus = 2
    h.memory = 4096
  end
  config.vm.synced_folder "~/.ssh", "/shares/.ssh"
  config.vm.synced_folder "~/.m2", "/shares/.m2"
  config.vm.synced_folder "../share", "/shares/files"

  config.vm.provision "shell" do |s|
    s.privileged = true
    s.path = "../shell/install_chocolatey.ps1"
  end
  config.vm.provision "shell" do |s|
    s.privileged = true
    s.path = "../shell/setup.ps1"
  end
  config.vm.provision "shell" do |s|
    s.privileged = true
    s.path = "../shell/final_setup.ps1"
  end
end
